# Copyright 2023 ManuelonGithub #
# SPDX-License-Identifier: MIT license #

PROGRAM ?= example-gpio

$(PROGRAM): $(wildcard *.c) $(wildcard *.h) $(wildcard *.S)

clean:
	rm -f $(PROGRAM) $(PROGRAM).hex
